config/routes.rb
Rails.application.routes.draw do
  resources :bigqueries
  devise_for :users
  resources :posts do
    resources :comments
  end

  resources :elecapps
   scope :api do
    get "/elecapps(.:format)"=> "elecapps#index"
    get "/elecapps/:id(.:format)" => 'elecapps#show'
   end

  root to: "home#index"
  get '/day' => 'usage#day'
  get '/week' => 'usage#week'
  get '/month' => 'usage#month'
  get '/blog' => 'posts#index'

end

app/models/bigquery.rb
class Bigquery < ActiveRecord::Base
end

app/controllers/bigqueries_controller.rb
class BigqueriesController < ApplicationController
  before_action :set_bigquery, only: [:show, :edit, :update, :destroy]

  # GET /bigqueries
  # GET /bigqueries.json
  def index
    render json: Elecapp.all   
  end

  # GET /bigqueries/1
  # GET /bigqueries/1.json
  def show
  end

  # GET /bigqueries/new
  def new
    @bigquery = Bigquery.new
  end

  # GET /bigqueries/1/edit
  def edit
  end

  # POST /bigqueries
  # POST /bigqueries.json
  def create
    @bigquery = Bigquery.new(bigquery_params)

    respond_to do |format|
      if @bigquery.save
        format.html { redirect_to @bigquery, notice: 'Bigquery was successfully created.' }
        format.json { render :show, status: :created, location: @bigquery }
      else
        format.html { render :new }
        format.json { render json: @bigquery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bigqueries/1
  # PATCH/PUT /bigqueries/1.json
  def update
    respond_to do |format|
      if @bigquery.update(bigquery_params)
        format.html { redirect_to @bigquery, notice: 'Bigquery was successfully updated.' }
        format.json { render :show, status: :ok, location: @bigquery }
      else
        format.html { render :edit }
        format.json { render json: @bigquery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bigqueries/1
  # DELETE /bigqueries/1.json
  def destroy
    @bigquery.destroy
    respond_to do |format|
      format.html { redirect_to bigqueries_url, notice: 'Bigquery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bigquery
      @bigquery = Bigquery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bigquery_params
      params.require(:bigquery).permit(:text, :number)
    end
end

app/helpers/bigqueries_helper.rb
module BigqueriesHelper
end

app/views/bigqueries/_form.html.erb
<%= simple_form_for(@bigquery) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :text %>
    <%= f.input :number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bigqueries/edit.html.erb
<h1>Editing Bigquery</h1>

<%= render 'form' %>

<%= link_to 'Show', @bigquery %> |
<%= link_to 'Back', bigqueries_path %>

app/views/bigqueries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bigqueries</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bigqueries.each do |bigquery| %>
      <tr>
        <td><%= bigquery.text %></td>
        <td><%= bigquery.number %></td>
        <td><%= link_to 'Show', bigquery %></td>
        <td><%= link_to 'Edit', edit_bigquery_path(bigquery) %></td>
        <td><%= link_to 'Destroy', bigquery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bigquery', new_bigquery_path %>

app/views/bigqueries/new.html.erb
<h1>New Bigquery</h1>

<%= render 'form' %>

<%= link_to 'Back', bigqueries_path %>

app/views/bigqueries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @bigquery.text %>
</p>

<p>
  <strong>Number:</strong>
  <%= @bigquery.number %>
</p>

<%= link_to 'Edit', edit_bigquery_path(@bigquery) %> |
<%= link_to 'Back', bigqueries_path %>