config/routes.rb
Rails.application.routes.draw do
  resources :bigqueries
  devise_for :users
  resources :posts do
    resources :comments
  end

  resources :elecapps
   scope :api do
    get "/elecapps(.:format)"=> "elecapps#index"
    get "/elecapps/:id(.:format)" => 'elecapps#show'
   end

  root to: "home#index"
  get '/day' => 'usage#day'
  get '/week' => 'usage#week'
  get '/month' => 'usage#month'
  get '/blog' => 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
   has_attached_file :image, styles: { medium: "700x500#", small: "350x250#" }
   validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
   @posts = Post.all.order("created_at DESC")
  end

  def show
  end

  def new
   @post = current_user.posts.build
  end

  def create
   @post = current_user.posts.build(post_params)
   if @post.save
    redirect_to @post
   else
    render 'new'
   end
  end

  def edit
  end

  def update
   if @post.update(post_params)
    redirect_to @post
   else
    render 'edit'
   end
  end

  def destroy
   @post.destroy
   redirect_to root_path
  end

  private
  def find_post
   @post = Post.find(params[:id])
  end

  def post_params
   params.require(:post).permit(:title, :link, :description, :image)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
        = f.input :image
        = f.input :title
	= f.input :link
	= f.input :description

	= f.submit

app/views/posts/edit.html.haml
%h1 Edit Post

= render 'form'

= link_to "Cancel", post_path

app/views/posts/index.html.haml
#posts
	- @posts.each do |post|
		.post
			%h2.title= link_to post.title, post
			%p.date
				Published at
				= time_ago_in_words(post.created_at)
				by
				= post.user.email
		#buttons
			- if user_signed_in?
				= link_to "New Post", new_post_path
			- else
				= link_to "Sign Up", new_user_registration_path
				= link_to "Sign In", new_user_session_path			

app/views/posts/new.html.haml
%h1 New Post

= render 'form'

app/views/posts/show.html.haml
#post_content
	%h1= @post.title
	%p= @post.content

	#comments
		%h2
			= @post.comments.count
			Comments
		= render @post.comments

		%h3 Reply to thread
		= render "comments/form"

	%br/
	%hr/
	%br/

	= link_to "Edit", edit_post_path(@post), class: "button"
	= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to do this?" }, class: "button"