config/routes.rb
Rails.application.routes.draw do
  resources :bigqueries
  devise_for :users
  resources :posts do
    resources :comments
  end

  resources :elecapps
   scope :api do
    get "/elecapps(.:format)"=> "elecapps#index"
    get "/elecapps/:id(.:format)" => 'elecapps#show'
   end

  root to: "home#index"
  get '/day' => 'usage#day'
  get '/week' => 'usage#week'
  get '/month' => 'usage#month'
  get '/blog' => 'posts#index'

end

app/views/layouts/application.html.haml
!!!5
%html
%head
	%title Plugin Pulse
	%meta{:name => "google-site-verification", :content => "5kpv9TCjwfa7k1-Hr8YOgYa_bQHC3vXgXD0HY_ekb1c"}
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	%link{ rel: "stylesheet", href: "http://fonts.googleapis.com/css?family=Lato:300,400,700", type: "text/css"}
	%link{:rel => "stylesheet", :href => "http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css"}
	%link{:rel => "stylesheet", :href => "http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"}	
	= csrf_meta_tags
%body
	%header.main_header.clearfix
		.wrapper
			#logo
				%p= link_to "PLUGIN ENERGY", root_path
			#buttons
				- if user_signed_in?		
					= link_to "Day", day_path(@day)
					= link_to "Week", week_path(@week)
					= link_to "Month", month_path(@month)
					= link_to "Blog", blog_path(@posts)
					= link_to "Account", edit_user_registration_path
					= link_to "Sign Out", destroy_user_session_path, method: :delete
				- else
					= link_to "Blog", blog_path(@posts)
					= link_to "Sign Up", new_user_registration_path
					= link_to "Sign In", new_user_session_path
	.wrapper
		%p.notice= notice
		%p.alert= alert

	.wrapper		
		= yield

app/views/layouts/haiwezi.html.erb
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" >
<head>
  <meta charset="utf-8" />
  <title>PlugIn</title>
  <style>
 	body{
   margin-top: 30px;
   margin-left:40px;
	}
  </style>
  	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>		
	<script src="http://code.highcharts.com/highcharts.js"></script>
	<script type="text/javascript">
	
		function uodate()
		{
		var values = [];
                var xdata = []
                var yes = '';
                $.getJSON('http://5.175.145.182/elecapps.json', function(data) {
                    // Populate series
                   // for (i = 0; i < data.length; i++){
                     //   processed_json.push([data.date[i].key, data.text[i].value]);
                   // }
                   for(i in data){
                   values.push(data[i].text);
                   xdata.push(data[i].date);
                   }
                   //console.log(yes);
                   console.log(values);
                   // draw chart
                    $('#container').highcharts({
                    chart: {
                        type: "column"
                    },
			plotOptions:{
				series:{
					animation:false
					}
				},
                    title: {
                        text: "The Plugin Team"
                    },
                    subtitle: {
                        text: 'Household Electricity Consumption'
                    },xAxis: {
                        categories:xdata,
                        allowDecimals: false,
                        title: {
                            text: ""
                        }
                    },
                    yAxis: {
                        title: {
                            text: "Usage in Watts"
                        }
                    },
                    series: [{
                            name: 'Consumption',
                        data: values
                    }]
                });
            });


	}

	function done()
	{
	setTimeout(function(){
	uodate();
	done();
		},300);
	}



        $(function () {
done();

/*
                var values = [];
		var xdata = []
                var yes = '';   
                $.getJSON('http://5.175.145.182/elecapps.json', function(data) {
                    // Populate series
                   // for (i = 0; i < data.length; i++){
                     //   processed_json.push([data.date[i].key, data.text[i].value]);
                   // }		      
                   for(i in data){
		   values.push(data[i].text);
		   xdata.push(data[i].date);
  		   }
                   //console.log(yes);
                   console.log(values); 
		   // draw chart
                    $('#container').highcharts({
                    chart: {
                        type: "column"
                    },
                    title: {
                        text: "The Plugin Team"
                    },
                    subtitle: {
			text: 'Household Electricity Consumption'
		    },
                    xAxis: {
                        categories:xdata,
                        allowDecimals: false,
                        title: {
                            text: ""
                        }
                    },
                    yAxis: {
                        title: {
                            text: "Usage in KWH"
                        }
                    },
                    series: [{
	                    name: 'Consumption',
                        data: values
                    }]
                }); 
            });
  */
      });
    </script>
 </head>
<body>
<div id="container"></div>
</body>
</html>